name: Deploy pipeline

on:
  workflow_run:
    workflows: ["Build pipeline"]
    types:
      - completed
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Pull Docker image
      run: sudo docker pull ramesh27/first:latest
    - name: Delete Old docker container
      run: sudo docker rm -f first-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 8090:8090 --name first-container ramesh27/first
